### ISSUE TITLE
Can You Add Windows 11 to Your Project?

### ISSUE THREAD

**Issue by inc-Majdev** [VergiliusProject/vergilius-project#13]
Could you add Windows 11 x64, please?
https://www.vergiliusproject.com/kernels/x64

**Comment by SergiusTheBest** [comment]
Windows 11 is not released yet.

**Comment by inc-Majdev** [comment]
SDK and WDK released. I don't think it will change. Could you please add Windows 11 20H2

**Comment by SergiusTheBest** [comment]
Ok, I'll take a look at it.

**Comment by SergiusTheBest** [comment]
Windows 11 Insider Preview is added.

**Comment by inc-Majdev** [comment]
thx
