### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by GanbaruTobi** [VergiliusProject/vergilius-project#22]
Only the Startpage is loading, nothing else:
https://www.vergiliusproject.com

**Comment by SergiusTheBest** [comment]
We don't see any issues on our side. Could you reload a page with cache (Ctrl+F5)? If that doesn't help take a look at the developer tools in a browser (especially the network tab).

You should see something like this:
![image](https://github.com/VergiliusProject/vergilius-project/assets/4660722/890280d5-43b1-4136-a258-9fdd1a12a4d0)
